version: '3.9'

services:
  postgres:
    container_name: devcomhub-postgres-1
    image: postgres:15.1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  zookeeper:
    container_name: devcomhub-zookeeper-1
    image: confluentinc/cp-zookeeper:5.2.7
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_txn_logs:/var/lib/zookeeper/log
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    container_name: devcomhub-kafka-1
    image: confluentinc/cp-kafka:5.3.8
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./create_topics.sh:/create-topics.sh
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-manager:
    container_name: devcomhub-kafka-manager-1
    image: hlebalbau/kafka-manager:stable
    restart: on-failure
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '9000:9000'
    environment:
      ZK_HOSTS: 'zookeeper:2181'

volumes:
  db_data: {}
  kafka_data: { }
  zookeeper_data: { }
  zookeeper_txn_logs: { }
